apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdond-capstone-deployment
  labels:
    app: cdond-capstone-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdond-capstone-service
  template:
    metadata:
      labels:
        app: cdond-capstone-service
    spec:
      containers:
      - name: web
        image: $AWS_ECR/project5:latest
        ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service loadbalance
spec:
  selector:
    app: cdond-capstone-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80